### ISSUE TITLE
Travis Build to verify unit test

### ISSUE THREAD

**Issue by staabm** [jquery-validation/jquery-validation#1724]
would be great if we would have a travis run, which build only takes the `tests` into account but not the actual changes in the `src` folder.
that way we could verify that newly added unit test fails without the patch.
This new build should be considered successfull when new tests were added and the unit test suite fails.

Maybe this is possible with a bit GIT fu, I dont know how it could work though.

**Comment by Arkni** [comment]
> This new build should be considered successfull when new tests were added and the unit test suite fails.

It's us who should consider it successful not Travis, I guess.

> Maybe this is possible with a bit GIT fu, I dont know how it could work though.

I have some ideas in mind, first we store the name of the current branch (`BRANCH`), then create a new branch for test only, then test the added tests and switch back to `BRANCH`. In other words:

```bash
> # get the last commit's hash of the current branch and store it
> BRANCH=$(git rev-parse HEAD)
> NEW_BRANCH="something"
> git checkout -b $NEW_BRANCH
> git reset origin/master
> git add test/
> git commit -m "Added tests"
> git reset --hard HEAD
```

Then run the tests. And switch back to `BRANCH`:

```bash
> git checkout $BRANCH
> git branch -D $NEW_BRANCH
```
and run the tests again.

we can add all that to `.travis.yml` file:
```yml
before_install:
  - export BRANCH=$(git rev-parse HEAD)
  - export NEW_BRANCH="something"
  - git checkout -b $NEW_BRANCH
  - git reset origin/master
  - git add test/
  - git commit -m "Added tests"
  - git reset --hard HEAD

after_install:
  - git checkout $BRANCH
  - git branch -D $NEW_BRANCH
  - npm test
```

_NOTES_:
> This will works only if the contributor added the test along with the change to src. but it's a good start I guess.
