### ISSUE TITLE
Using Milk as the model: Problem, issue overcome and added good stuff

### ISSUE THREAD

**Issue by lzw8bk** [jquery-validation/jquery-validation#204]
Great plugin and am delighted:

Here's a problem I can't seem to fix:

The Milk demo adds a green "checked" image to a field with no errors.
It also adds the red "unchecked" image and error message on errors detected.
If I change a field that was originally valid to has errors, the error message is displayed but the image remains as the original green "checked." I can't figure out how to also change the image back to "unchecked." All of my code is submitted below.

See http://smartplantools.com/register/

Issue overcome with "maskedinput"

Example for "maskedinput" shows this code: 
`$("input.phone").mask("(999) 999-9999");`
and it did not get enabled (my form has <input id="phone" ...

Changed to this code: 
`$("input.#phone").mask("(999) 999-9999");`
and it works great! Also check out the remote phone.php in the code below to alert on incomplete entry

Good stuff added

I can take registrations from the US and Canada. I wanted to not only display the appropriate "select" based on US states or Canadian provinces but also display different Zip or Canada Postal Code input forms.

Did it with the depend on edit using the country selector and added a blur function on country. :-)

Here's my code in reference to the above:

``` js
$(document).ready(function() {
  // validate signup form on keyup and submit
  var validator = $("#signupform").validate({
    rules: {
      firstname: "required",
      lastname: "required",
      company: "required",
      street: "required",
      city: "required",
      country: "required",
      state: "required",
      zip: {
          required: function(element) {
                    return $("#country").val() == 'US';
                    },
          rangelength: [5,5],
          remote: "zip-us.php"
      },
      cazip1: {
          required: function(element) {
                    return $("#country").val() == 'CA';
                    },
          rangelength: [3,3],
          remote: "zip-ca1.php"
      },
      cazip2: {
          required: function(element) {
                    return $("#country").val() == 'CA';
                    },
          rangelength: [3,3],
          remote: "zip-ca2.php"
      },
      phone: {
          required: true,
          remote: "phone.php"
      },
      username: {
        required: true,
        minlength: 2,
        remote: "users.php"
      },
      password: {
        required: true,
        minlength: 5
      },
      password_confirm: {
        required: true,
        minlength: 5,
        equalTo: "#password"
      },
      email: {
        required: true,
        minlength: 8,
        email: true,
        remote: "emails.php"
      },
      terms: "required"
    },
    messages: {
      firstname: "Enter your firstname",
      lastname: "Enter your lastname",
      company: "Enter your comapny name",
      street: "Enter your street address",
      city: "Enter your city",
      country: "Select your country",
      state: "Select your state/province",
      zip: {
        required: "Enter your US/PR postal code",
        rangelength: "{0} numeric digits required",
        remote: jQuery.format("{0} is an invalid ZIP Code")
      },
      cazip1: {
        required: "Enter in 2 parts<br/>",
        rangelength: "{0} alpha-numeric digits [ANA]<br/>",
        remote: jQuery.format("{0} is an invalid code<br/>")
      },
      cazip2: {
        required: "Enter in 2 parts<br/>",
        rangelength: "{0} alpha-numeric digits [NAN]<br/>",
        remote: jQuery.format("{0} is an invalid code")
      },
      phone: {
        required: "Enter your phone #",
        remote: jQuery.format("Entry not complete, re-enter")
      },
      username: {
        required: "Enter a username",
        minlength: jQuery.format("{0} characters required"),
        remote: jQuery.format("{0} is already in use")
      },
      password: {
        required: "Provide a password",
        minlength: jQuery.format("{0} characters required")
      },
      password_confirm: {
        required: "Repeat your password",
        minlength: jQuery.format("{0} characters required"),
        equalTo: "Password does not match"
      },
      email: {
        required: "Email address required",
        minlength: "This email looks too short",
        email: jQuery.format("Not a valid email address"),
        remote: jQuery.format("{0} already registered")
      },
      terms: "You must agree to the License Agreement"
    },
    // the errorPlacement has to take the table layout into account
    errorPlacement: function(error, element) {
      if ( element.is(":radio") ) 
        error.appendTo( element.parent().next().next() );
      else if ( element.is(":checkbox") ) 
        error.appendTo ( element.next() );
      else if ( element.is(":text") )
        error.appendTo( element.parent().next() );
      else 
        error.appendTo( element.parent().next() );
    },
    // specifying a submitHandler prevents the default submit, good for the demo
    submitHandler: function() {
      alert("submitted!");
    },
    // Use this one when ready
    submitHandler: function(form) {
      form.submit();
    },
    // set this class to error-labels to indicate valid fields
    success: function(label) {
      // set &nbsp; as text for IE
      label.html("&nbsp;").addClass("checked");
    }

  });

$("input.#phone").mask("(999) 999-9999");
//    $("input.zip").mask("99999");
//    $("input.cazip").mask("*** ***");

$("#country").blur(function() {
  request = $("#country").val();
  if (request == 'US') {
    $("#selectUS").css("display","table-row");
    $("#selectCA").css("display","none");
    $("#dzip").css("display","table-row");
    $("#dcazip").css("display","none");
  }
  else {
    $("#selectUS").css("display","none");
    $("#selectCA").css("display","table-row");
    $("#dzip").css("display","none");
    $("#dcazip").css("display","table-row");
  }
    $("#zip").valid();
    $("#cazip1").valid();
    $("#cazip2").valid();
});
/*
$("#country").blur(function() {
  $("#zip").valid();
});
$("#country").blur(function() {
  $("#cazip1").valid();
});
$("#country").blur(function() {
  $("#cazip2").valid();
});
*/

  // propose username by combining first and lastname
  $("#username").focus(function() {
    var firstname = $("#firstname").val();
    var lastname = $("#lastname").val();
    if(firstname && lastname && !this.value) {
      this.value = firstname + " " + lastname;
    }
  });

});

$.fn.hoverClass = function(classname) {
  return this.hover(function() {
    $(this).addClass(classname);
  }, function() {
    $(this).removeClass(classname);
  });
};
```

remote phone.php:

``` php
<?php
$phone = trim($_REQUEST['phone']);
$valid = 'true';
  if (preg_match('/_/', $phone)) //
      {
    $valid = 'false';
      }
echo $valid;
?>
```

remote zip-ca1:

``` php
<?php
$request = strtoupper(trim($_REQUEST['cazip1']));
$valid = 'true';
$result = preg_match('/[ABCEGHJKLMNPRSTVXY]{1}\d{1}[A-Z]{1}/', $request);
if (!$result)
      {
    $valid = 'false';
      }
echo $valid;
?>
```

remote zip-ca2:

``` php
<?php
$request = strtoupper(trim($_REQUEST['cazip2']));
$valid = 'true';
$result = preg_match('/\d[A-Z]\d/', $request);
if (!$result)
      {
    $valid = 'false';
      }
echo $valid;
?>
```

milk css:

``` css
/* GENERAL ELEMENTS */

* { margin: 0; padding: 0; }

body, label, input, select, textarea { font-family: verdana, arial, helvetica, sans-serif; font-size: 13px; }
body { color: #333;  background-color: #fff; text-align: center; }

a:link { color:#0060BF; text-decoration: underline; }
a:visited { color:#0060BF; text-decoration: underline; }
a:active { color:#0060BF; text-decoration: underline; }
a:hover { color:#000000; text-decoration: underline; }

img { border: 0px; }

/* p { font-size: 1.0em; line-height: 1.3em; margin: 1.2em 0em 1.2em 0em; } */
li > p { margin-top: 0.2em; }
pre { font-family: monospace; font-size: 1.0em; text-align: left; }
strong, b { font-weight: bold; }
option { padding-left: 10px; font-family: verdana, sans-serif; }

/* PAGE ELEMENTS */

/* Content */

label { font-weight: normal; }
#reminders label { font-weight: normal; }
#hdsubmit { width: 60px; }

table.tabbedtable { padding-left: 3em; }
table.tabbedtable td { padding-bottom: 5px; }
table.tabbedtable label { text-align: right; padding-right: 9px; }
.hiddenlabel { visibility: hidden; }
.largelink { border: 1px solid #cacaca; padding: 10px; background-color: #E8EEF7; font-size: 1.2em; font-weight: bold; }
.largelinkwrap { padding-top: 10px; padding-bottom: 10px; }
input { width: 165px; }

#signuptab {
  float:left;
  width:100%;
  background:#fff url("bg.gif") repeat-x bottom;
  font-size: 1.0em;
  line-height: normal;
}
#signuptab ul {
  margin:0;
  padding: 0px 10px 0px 10px;
  list-style:none;
}
#signuptab li {
  float:left;
  background:url("left_white.png") no-repeat left top;
  margin:0;
  padding:0 3px 0 9px;
  border-bottom:1px solid #CACACA;
}
#signuptab a {
  float:left;
  display:block;
  width:.1em;
  background:url("right_white.png") no-repeat right top;
  padding:2px 15px 0px 6px;
  text-decoration:none;
  font-weight:normal;
  color:#fff;
  white-space: nowrap;
}
#signuptab > ul a {width:auto;}
/* Commented Backslash Hack hides rule from IE5-Mac \*/
#signuptab a {float:none;}
/* End IE5-Mac hack */
#signuptab a:hover {
  color:#333;
}
#signuptab #signupcurrent {
  background-position:0 -150px;
  border-width:0;
}
#signuptab #signupcurrent a {
  background-position:100% -150px;
  padding-bottom:1px;
  color:#000;
}
#signuptab li:hover, #signuptab li:hover a {
  background-position:0% -150px;
  color:#000;
}
#signuptab li:hover a {
  background-position:100% -150px;
}

/* Signup box */

#signupbox {
  width: 100%;
  text-align: center;
  margin: 0em auto;
}

#signupwrap {
  border: 1px solid #CACACA;
  border-top: 0;
  text-align: left;
  padding: 15px 0px 15px 0px;
  clear: both;
}

/* Unsupported browsers */

.orange_rbcontent { padding: 0.4em; }
.orange_rbroundbox { width: 100%; }

#unsupported {
  font-weight: bold;
  text-align: left;
}

/*#content {
  padding-top: 15px;
}*/

/* Signup form */

#signupform table {
  border-spacing: 0px;
  border-collapse: collapse;
  empty-cells: show;
  width: 570px;
}

#signupform tr#selectUS { display: none; } 
#signupform tr#selectCA { display: none; } 
#signupform tr#dzip { display: none; } 
#signupform tr#dcazip { display: none; } 

#signupform td.label {
  padding-top: 2px;
  padding-right: 8px;
  vertical-align: top;
  text-align: right;
  width: 160px;
  white-space: nowrap;
}

#signupform td.field{
  padding-bottom: 10px;
  white-space: nowrap;
  width: 170px;
}

#signupform .status {
  padding-top: 2px;
  padding-left: 8px;
  vertical-align: top;
  width: 240px;
  font-size: 11px !important;
/*  white-space: nowrap; */
}

#signupform .textfield {
  width: 170px;
}

#signupform label.error {
  background:url("images/unchecked.png") no-repeat 0px 0px;
  padding-left: 21px;
  padding-bottom: 3px;
  font-weight: normal;
  color: #990000;
  font-size: 11px !important;
}


#signupform #lterms label.error {
  background:url("images/unchecked.png") no-repeat 0px 0px;
  padding-left: 21px;
  padding-bottom: 3px;
  margin-left: 5px;
  font-weight: normal;
  color: #990000;
}


#signupform label.checked {
  background:url("images/checked.png") no-repeat 0px 0px;
}


#signupform #lterms label.checked {
  background:url("images/checked.png") no-repeat 0px 0px;
}

#signupform .success_msg {
  font-weight: bold;
  color: #0060BF;
  margin-left: 19px;
}

#signupform #dateformatStatus, #signupform #termsStatus {
  margin-left: 6px;
}

#signupform #dateformat_eu {
 vertical-align: middle;
}

#signupform #ldateformat_eu {
  font-weight: normal;
  vertical-align: middle;
}

#signupform #dateformat_am {
  vertical-align: middle;
}

#signupform #ldateformat_am {
  font-weight: normal;
  vertical-align: middle;
}

#signupform #termswrap {
  float: left;
  width: 410px;
}

#signupform #terms {
  vertical-align: middle;
  float: left;
  display: block;
  margin-right: 5px;
  margin-top: 3px !important;
  width: 20px;
}

#signupform #lterms {
  font-weight: normal;
  vertical-align: top;
  float: left;
  display: block;
  white-space: normal;
}

#signupform #lsignupsubmit {
  visibility: hidden;
}
```
